name: argos-translate
title: Argos Translate
base: core18 
version: '1.6.1'
license: MIT
summary: Offline neural machine translation app
description: |
  Open-source offline neural machine translation app that allows installing packages to support new languages.

  Automatically installs and connects to `argos-translate-base-langs` snap to support translations between Arabic, Chinese, English, French, Russian, and Spanish.

  Additional languages can be installed from *.argosmodel files or from supplementary content snaps:
  * argos-translate-de-en - German - English
  * argos-translate-en-it - English - Italian
  * argos-translate-en-pt - English - Portuguese

  To connect automatically:
  `sudo snap connect argos-translate:argos-packages argos-translate-en-it:argos-packages`

  Code/Documentation: https://github.com/argosopentech/argos-translate
icon: snap/gui/icon.png
grade: stable
confinement: strict

apps:
  argos-translate: 
    adapter: full
    command: desktop-launch $SNAP/bin/argos-translate-gui
    environment:
      DISABLE_WAYLAND: 1
    plugs:
      - desktop
      - desktop-legacy
      - network
      - opengl
      - wayland
      - x11
  cli: 
    command: bin/argos-translate
 
# From snapcraft-desktop-helpers
# https://github.com/ubuntu/snapcraft-desktop-helpers
parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  argos-translate:
    after: [desktop-qt5]
    plugin: python
    python-version: python3
    source: .
    # Based on ericoporto/pyqthelloworld
    # https://github.com/ericoporto/pyqthelloworld
    build-packages:
      - python3
      - python3-pyqt5
      - execstack
    stage-packages:
      - python3
      - python3-pyqt5
      - libc-bin
      - locales

  model-files:
    source: snap_custom/
    source-type: local
    plugin: dump
    organize:
      '*' : snap_custom/

plugs:
  argos-packages:
    interface: content
    content: argos-packages
    target: $SNAP/snap_custom/content_snap_packages
    default-provider: argos-translate-base-langs

